[package]
name = "sqlite"
version = "0.1.0"
edition = "2024"

[dependencies]
ariadne = "0.5.1"
chumsky = { version = "0.10.1", features = ["pratt"] }
clap = { version = "4.5.55", features = ["derive"] }
memmap2 = "0.9.9"
rustyline = "17.0.2"
thiserror = "2.0.12"
